[package]
name = "libp2p-bitswap"
version = "0.11.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Implementation of the ipfs bitswap protocol."
license = "MIT OR Apache-2.0"
repository = "https://github.com/ipfs-rust/libp2p-bitswap"

[dependencies]
async-trait = "0.1.42"
fnv = "1.0.7"
futures = "0.3.8"
libipld = { version = "0.9.0", default-features = false }
libp2p = { version = "0.33.0", default-features = false, features = ["request-response"] }
prometheus = "0.11.0"
thiserror = "1.0.23"
tracing = "0.1.22"
unsigned-varint = { version = "0.5.1", features = ["futures", "std"] }

[dev-dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
env_logger = "0.8.2"
libipld = { version = "0.9.0", default-features = false, features = ["dag-cbor"] }
libp2p = "0.33.0"
multihash = { version = "0.13.2", default-features = false, features = ["blake3"] }

[patch.crates-io]
libp2p = { path = "../rust-libp2p" }
