[package]
name = "libp2p-bitswap"
version = "0.8.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Implementation of the ipfs bitswap protocol."
license = "MIT OR Apache-2.0"
repository = "https://github.com/ipfs-rust/libp2p-bitswap"

[dependencies]
async-trait = "0.1.41"
fnv = "1.0.7"
futures = "0.3.5"
libipld = { version = "0.7.0", default-features = false }
libp2p = { version = "0.28.1", default-features = false, features = ["request-response"] }
log = "0.4.11"
thiserror = "1.0.20"
unsigned-varint = { version = "0.5.1", features = ["futures", "std"] }

[dev-dependencies]
async-std = { version = "1.6.5", features = ["attributes"] }
env_logger = "0.7.1"
libipld = { version = "0.7.0", default-features = false, features = ["dag-cbor"] }
libp2p = "0.28.1"
